function [q,qr,qz] = q_fun(r0,a,b,c,r,z)
%Q_FUN
%    [Q,QR,QZ] = Q_FUN(R0,A,B,C,R,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 01:06:29

t2 = 1.0./c;
t3 = -r;
t4 = -z;
t5 = a+t3;
t6 = b+t4;
t7 = t5.^2;
t8 = t6.^2;
t9 = t7+t8;
t10 = sqrt(t9);
t11 = 1.0./t10;
t12 = -t10;
t13 = r0+t12;
t14 = t2.*t13;
t15 = tanh(t14);
q = t15;
if nargout > 1
    t16 = t15.^2;
    t17 = t16-1.0;
    qr = t2.*t11.*t17.*(a.*2.0-r.*2.0).*(-1.0./2.0);
end
if nargout > 2
    qz = t2.*t11.*t17.*(b.*2.0-z.*2.0).*(-1.0./2.0);
end
