function ae = myAeVe(e,m,r,u,ur,uz,q)
%MYAEVE
%    AE = MYAEVE(E,M,R,U,UR,UZ,Q)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-May-2021 02:06:31

ae = sqrt(2.0).*r.*pi.*(tanh(q./m)./2.0-1.0./2.0).*((u.^2-1.0).^2./(e.*4.0)+(e.*(ur.^2+uz.^2))./2.0).*(-3.0./2.0);
