function options = arcset(varargin)


if rem(nargin,2) ~= 0
    error('Arguments must occur in name-value pairs.');
end
% set default option properties to output
options = struct(...
    'newitr',100,...
    'newer',1e-4,...
    'newlimitr',12,...
    'parchart',0,...
    'stpdec',0.5,...
    'stpinc',1.2,...
    'stpmin',1e-4,...
    'stpmax',1e-1,...
    'startinc',1,...
    'startdec',0,...
    'alwaysinc',0,...
    'alwaysdec',0,...
    'inxdot',2);

names = lower(fieldnames(options));
i = 1;  charchk = 1;
while i <= nargin
    arg = varargin{i};
    if charchk
        j = strcmpi(arg,names);
        if isempty(j) % if no matches
            error('Unrecognized property name ''%s''.', arg);
        else
            j = find(j,1);
        end
        charchk = 0;  % naxt varargin must be number
    else
        options.(names{j}) = arg;
        charchk = 1;
    end
    i = i + 1;
end
end
